#!/bin/sh

for p in $(cat demo/plugins.txt | perl -pe s/:.+//g | grep -E 'workflow-|pipeline-' | grep -v 'pipeline-rest-api' | grep -v 'workflow-aggregator'); do
  cd ../$p-plugin
  git fetch upstream
  git fetch origin
  git checkout master
  git merge upstream/master
done
